#!/usr/bin/python

import RPi.GPIO as GPIO
import sys
import subprocess
import os
import glob
import time
#import image

GPIO.setmode(GPIO.BOARD)

# GPIO 17 is set up as input, pulled up to avoid false detection.
# The Port is wired to connect to GND on button press.  
# So we'll be setting up falling edge detection
GPIO.setup(17, GPIO.IN, pull_up_down=GPIO.PUD_UP)

path ='/media/usb/'
imgpath = '/media/usb/Thank_You.jpg'
#imgfile in glob.glob(os.path.join(path, 'Thank_You.jpg'))

def displayThanks(channel):
	print("Event change detected.")
	#displaying the image
	image=Image.open(os.path.join(path, 'Thankyou.jpg'))
	image.show()
	time.sleep(5)
	#Take input from the numeric keypad
	raw_input("Enter your number from the keypad\n>")
	#Do the printer job over here.
	#Print job command starts over here.
	#The printer should be replaced with the actual printer name.
	a = subprocess.call( [ "lp", "-d", "printer", "/home/pi/omxloop" ] )

while(1):
        for infile in glob.glob(os.path.join(path, '*.mp4')):
			a = subprocess.call( [ "clear" ] )
			a = subprocess.call( [ "omxplayer", "--live", "--aspect-mode", "fill", "-o", "hdmi", infile, "-b" ] )
            #GPIO.add_event_detect(17, GPIO.RISING, callback=displayThanks, bouncetime=350)

